env:
  node: true
  es6: true
parserOptions:
  ecmaVersion: 2017
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console:
    - off
  no-constant-condition:
    - error
    - checkLoops: false
