#!/bin/bash

chmod +x ./scripts/run
chmod +x ./scripts/sass

# Find FireFox binary
# TODO
ff_bin=/Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox-bin

# Write the binary path to disk
echo -n "$ff_bin" > ./ff_bin_path.txt